config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to:'homes#top'
    get 'about'=>'homes#about',as:'about'

    get 'customers/my_page'=>'customers#show'
    get 'customers/information/edit'=>'customers#edit'
    patch 'customers/information'=>'customers#update'
    get 'customers/confirm'=>'customers#confirm'
    patch '/customers/withdrawal'=>'customers#withdrawal'

    resources:items,only:[:index,:show]
    resources:cart_items,only:[:index,:create,:update,:destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources:orders,only:[:new,:create,:index,:show] do
      collection do
        post 'confirm'
        get  'done'
      end
    end
    resources:addresses,only:[:create,:index,:edit,:update,:destroy]
  end

  get 'admin'=>'admin/homes#top',as:'admin'

  namespace :admin do
    resources:items,only:[:new,:create,:index,:show,:edit,:update]
    resources:genres,only:[:create,:index,:edit,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:orders,only:[:show,:update] do
      resources:order_details,only:[:update]
    end
  end


  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached:image
  has_many:cart_items,    dependent: :destroy
  has_many:order_details, dependent: :destroy
  belongs_to:genre

  validates :name,         presence:true
  validates :introduction, length:{ minimum:1,maximum:255 }
  validates :genre_id,     presence:true
  validates :price,        presence:true
  validates :is_active,    inclusion: ["sale","suspended_sales"]


  enum is_active: {sale:true,suspended_sales:false}

  def with_tax_price
    (price*1.1).floor
  end

  def get_image(width,height)
    unless image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    image.variant(resize_to_limit:[width,height]).processed
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action:authenticate_admin!
  
  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
       flash[:notice]="登録に成功しました。"
       redirect_to admin_item_path(@item.id)
    else
      render:new
    end
  end

  def index
    @items=Item.page(params[:page])
  end

  def show
    @item=Item.find(params[:id])
    
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice]="変更に成功しました。"
      redirect_to admin_item_path(@item.id)
    else
      render:edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">

  <div class="m-3">
    <% if @item.errors.any? %>
      <h5><%= @item.errors.count %>件のエラーが発生しました。</h5>
      <% @item.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>
  </div>

  <h5 class="m-5"><span class="bg-light">　商品編集　</span></h5>

  <%= form_with model:@item,url:admin_item_path(@item.id),method: :patch do |f| %>
    <div class="row justify-content-center">
      <label for="itemImage" class="col-lg-2 col-sm-4 col-form-label">商品画像</label>
      <div class="col-lg-6 col-sm-8">
        <%= f.file_field:image,accept:"image/*",id:"itemImage" %>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="itemName" class="col-lg-2 col-sm-4 col-form-label">商品名</label>
      <div class="col-lg-6 col-sm-8">
        <%= f.text_field:name,id:"itemName", :size=>"30" %>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="itemIntroduction" class="col-lg-2 col-sm-4 col-form-label">商品説明</label>
      <div class="col-lg-6 col-sm-8">
        <%= f.text_area:introduction,size:"30x7",id:"itemIntroduction" %>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="genre" class="col-lg-2 col-sm-4 col-form-label">ジャンル</label>
      <div class="col-lg-6 col-sm-8 pt-1">
        <%= f.select:genre_id,options_from_collection_for_select(Genre.all,:id,:name),{},{class:"select"} %>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="price" class="col-lg-2 col-sm-4 col-form-label">税抜価格</label>
      <div class="col-lg-6 col-sm-8">
        <p><%= f.text_field:price,id:"price", :size=>"30" %>円</p>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="is_active" class="col-lg-2 col-sm-4 col-form-label">販売ステータス</label>
      <div class="col-lg-6 col-sm-8 pt-2">
        <%= f.radio_button:is_active,"sale",id:"is_active" %>
        <%= f.label:is_active,"販売中",{style: "display: inline-block;"} %>
        <%= f.radio_button:is_active,"suspended_sales",class:"ml-3" %>
        <%= f.label:is_active,"販売停止中",{style: "display: inline-block;"} %>
      </div>
    </div>

  　<div class="row justify-content-center">
　　　<div class="offset-lg-2 offset-3 col-lg-6 col-sm-7 pt-2">
        <%= f.submit"変更を保存",class:"btn btn-success col-md-4 col-7" %>
      </div>
    </div>

  <% end %>

</div>

app/views/admin/items/index.html.erb
<div class="container">

  <div class="row d-flex justify-content-between m-5">
    <h5><span class="bg-light">　商品一覧　</span></h5>
    <%= link_to new_admin_item_path do %>
      <i style="width:30px;height: 30px;" class="far fa-plus-square text-dark"></i>
    <% end %>
  </div>

  <div class="row">
    <table class="table table-borderless text-nowrap">
      <thead>
        <tr class="table-secondary">
          <th style="width: 10%">商品ID</th>
          <th style="width: 30%">商品名</th>
          <th style="width: 10%">税抜価格</th>
          <th style="width: 30%">ジャンル</th>
          <th style="width: 20%">ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to admin_item_path(item.id),class:"text-dark border-bottom border-dark" do %>
                <%= item.name %>
              <% end %>
          </td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
              <% if item.is_active=="sale" %>
                <td class="text-success"><%= Item.is_actives_i18n[:"#{item.is_active}"] %></td>
              <% else %>
                <td class="text-secondary"><%= Item.is_actives_i18n[:"#{item.is_active}"] %></td>
              <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">

  <div class="m-3">
    <% if @item.errors.any? %>
      <h5><%= @item.errors.count %>件のエラーが発生しました。</h5>
      <% @item.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>
  </div>

  <h5 class="m-5"><span class="bg-light">　商品新規登録　</span></h5>

  <%= form_with model:@item,url:'/admin/items',method: :post do |f| %>
    <div class="row justify-content-center">
      <label for="itemImage" class="col-lg-2 col-sm-4 col-form-label">商品画像</label>
      <div class="col-lg-6 col-sm-8">
        <%= f.file_field:image,accept:"image/*",id:"itemImage" %>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="itemName" class="col-lg-2 col-sm-4 col-form-label">商品名　</label>
      <div class="col-lg-6 col-sm-8">
        <%= f.text_field:name,id:"itemName", :size=>"30",placeholder:"商品名" %>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="itemIntroduction" class="col-lg-2 col-sm-4 col-form-label">商品説明</label>
      <div class="col-lg-6 col-sm-8">
        <%= f.text_area:introduction,size:"30x7",id:"itemIntroduction",placeholder:"ここに説明文を記述します" %><br>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="genre" class="col-lg-2 col-sm-4 col-form-label">ジャンル</label>
      <div class="col-lg-6 col-sm-8 pt-1">
        <%= f.select:genre_id,options_from_collection_for_select(Genre.all,:id,:name),{include_blank:'--選択してください--'},{class:"select",required: true} %>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="price" class="col-lg-2 col-sm-4 col-form-label">税抜価格</label>
      <div class="col-lg-6 col-sm-8">
        <p><%= f.text_field:price,id:"price", :size=>"30",placeholder:"1000" %>円</p>
      </div>
    </div>

    <div class="row justify-content-center">
      <label for="is_active" class="col-lg-2 col-sm-4 col-form-label">販売ステータス</label>
      <div class="col-lg-6 col-sm-8 pt-2">
        <%= f.radio_button:is_active,"sale",id:"is_active",checked:true %>
        <%= f.label:is_active,"販売中",{style: "display: inline-block;"} %>
        <%= f.radio_button:is_active,"suspended_sales",class:"ml-3" %>
        <%= f.label:is_active,"販売停止中",{style: "display: inline-block;"} %>
      </div>
    </div>

　　<div class="row justify-content-center">
　　　<div class="offset-lg-2 offset-2 col-lg-6 col-sm-7 pt-2">
        <%= f.submit"新規登録",class:"btn btn-success col-4" %>
      </div>
    </div>

  <% end %>

</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="m-5"><span class="bg-light">　商品詳細　</span></h5>
  </div>

  <div class="row">
    <div class="col-md-3 text-center mt-3">
    <%= image_tag @item.get_image(200,200) %>
   </div>

    <div class="offset-sm-1 col-md-8 mt-3">
      <table class="table table-borderless ml-4">
      <tr><th style="width: 30%">商品名</th><td style="width: 70%"><%= @item.name %></td></tr>
      <tr><th style="width: 30%">商品説明</th><td style="width: 70%"><%= @item.introduction %></td></tr>
      <tr><th style="width: 30%">ジャンル</th><td style="width: 70%"><%= @item.genre.name %></td></tr>
      <tr><th style="width: 30%">税込価格<br>(税抜価格)</th><td style="width: 70%"><%= (@item.price*1.1).floor.to_s(:delimited)%>(<%= @item.price.to_s(:delimited) %>)円</td></tr>
      <tr><th style="width: 30%" class="text-nowrap">販売ステータス</th>
          <% if @item.is_active=="sale" %>
            <td style="width: 70%" class="text-success"><%= Item.is_actives_i18n[:"#{@item.is_active}"]%></td>
          <% else %>
            <td style="width: 70%" class="text-secondary"><%= Item.is_actives_i18n[:"#{@item.is_active}"]%></td>
          <% end %>
      </tr>
      </table>
    </div>
      <%=link_to edit_admin_item_path(@item.id),class:"btn btn-success col-sm-2 col-8 mx-auto mt-2" do %>
        <%="編集する" %>
      <% end %>

  </div>
</div>