config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to:'homes#top'
    get 'about'=>'homes#about',as:'about'

    get 'customers/my_page'=>'customers#show'
    get 'customers/information/edit'=>'customers#edit'
    patch 'customers/information'=>'customers#update'
    get 'customers/confirm'=>'customers#confirm'
    patch '/customers/withdrawal'=>'customers#withdrawal'

    resources:items,only:[:index,:show]
    resources:cart_items,only:[:index,:create,:update,:destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources:orders,only:[:new,:create,:index,:show] do
      collection do
        post 'confirm'
        get  'done'
      end
    end
    resources:addresses,only:[:create,:index,:edit,:update,:destroy]
  end

  get 'admin'=>'admin/homes#top',as:'admin'

  namespace :admin do
    resources:items,only:[:new,:create,:index,:show,:edit,:update]
    resources:genres,only:[:create,:index,:edit,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:orders,only:[:show,:update] do
      resources:order_details,only:[:update]
    end
  end


  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:cart_items, dependent: :destroy
  has_many:orders,     dependent: :destroy
  has_many:addresses,  dependent: :destroy

  validates :last_name,presence:true
  validates :first_name,presence:true
  validates :last_name_kana,presence:true
  validates :first_name_kana,presence:true
  validates :postal_code,presence:true
  validates :address,presence:true
  validates :telephone_number,presence:true
  validates :is_deleted,inclusion: ["valid","withdrawal"]

  enum is_deleted: {valid: false,withdrawal: true},_suffix: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action:authenticate_admin!

  def index
    @customers=Customer.page(params[:page])
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice]="変更に成功しました"
      redirect_to admin_customer_path(@customer.id)
    else
      @customer.last_name=Customer.find(params[:id]).last_name
      @customer.first_name=Customer.find(params[:id]).first_name
      render:edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

  <div class="m-3">
    <% if @customer.errors.any? %>
      <h5><%= @customer.errors.count %>件のエラーが発生しました。</h5>
      <% @customer.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>
  </div>

  <h5 class="m-5"><span class="bg-light">　<%= "#{@customer.last_name}#{@customer.first_name}" %>さんの会員情報編集　</span></h5>

  <%= form_with model:@customer,url:admin_customer_path(@customer.id),method: :patch do |f| %>
  <div class="row">
    <%= f.label :id,"会員ID",class:"col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= @customer.id %>
    </div>
  </div>

  <div class="row">
    <label for="name" class="col-md-2 col-form-label">氏名</label>
    <div class="col-xl-2 col-lg-3 col-md-4">
      <%= f.text_field:last_name,id:"name" %>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4">
     <%= f.text_field:first_name,id:"name" %>
    </div>
  </div>

  <div class="row">
    <label for="kana" class="col-md-2 col-form-label">フリガナ</label>
    <div class="col-xl-2 col-lg-3 col-md-4">
      <%= f.text_field:last_name_kana,id:"kana" %>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4">
      <%= f.text_field:first_name_kana %>
    </div>
  </div>

  <div class="row">
    <label for="postal" class="col-md-2 col-form-label">郵便番号</label>
    <div class="col-md-3">
      <%= f.text_field:postal_code,id:"postal" %>
    </div>
  </div>

  <div class="row">
    <label for="address" class="col-md-2 col-form-label">住所</label>
    <div class="col-md-7">
      <%= f.text_field:address,id:"address", :size=>"70" %>
    </div>
  </div>

  <div class="row">
    <label for="telephone" class="col-md-2 col-form-label">電話番号</label>
    <div class="col-md-3">
      <%= f.telephone_field:telephone_number,id:"telephone" %>
    </div>
  </div>

  <div class="row">
    <label for="email" class="col-md-2 col-form-label text-nowrap">メールアドレス</label>
    <div class="col-md-3">
      <%= f.email_field:email,id:"email" %>
    </div>
  </div>

  <div class="row">
    <label for="status" class="col-md-2 col-form-label text-nowrap">会員ステータス</label>
    <div class="col-md-3 mt-2">
      <%= f.radio_button:is_deleted,"valid",id:"status" %>
      <%= f.label:is_deleted,"有効",{style: "display :inline-block"} %>
      <%= f.radio_button:is_deleted,"withdrawal",class:"ml-3" %>
      <%= f.label:is_deleted,"退会",{style: "display :inline-block"} %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 col-form-label"></div>
    <div class="col-md-3">
      <%= f.submit"変更を保存",class:"btn btn-success mt-4" %>
    </div>
  </div>

  <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">

 <h5 class="m-5"><span class="bg-light">　会員一覧　</span></h5>

<table class="table w-75 mx-auto text-nowrap">
  <thead>
    <tr class="table-secondary">
      <th style="width: 15%">会員ID</th>
      <th style="width: 30%">氏名</th>
      <th style="width: 30%">メールアドレス</th>
      <th style="width: 25%">ステータス</th>
    </tr>

    <% @customers.each do |customer| %>

      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to "#{customer.last_name}#{customer.first_name}",admin_customer_path(customer.id),class:"text-dark border-bottom border-dark" %></td>
        <td><%= customer.email %></td>
        <% if customer.is_deleted=="valid" %>
          <td class="text-success"><%= Customer.is_deleteds_i18n[:"#{customer.is_deleted}"] %></td>
        <% else %>
          <td class="text-secondary"><%= Customer.is_deleteds_i18n[:"#{customer.is_deleted}"] %></td>
        <% end %>
      </tr>
     <% end %>
  </thead>
</table>
<%= paginate @customers %>

</div>

app/views/admin/customers/show.html.erb
<div class="container">

  <h5 class="mt-5 mb-5"><span class="bg-light">　<%= "#{@customer.last_name}#{@customer.first_name}" %>さんの会員詳細　</span></h5>

  <div class="row">
    <table class="table table-borderless text-nowrap">
      <tr>
        <th>会員ID</th><td><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th><td><%= "#{@customer.last_name} #{@customer.first_name}" %></td>
      </tr>
      <tr>
        <th>フリガナ</th><td><%= "#{@customer.last_name_kana} #{@customer.first_name_kana}" %></td>
      </tr>
      <tr>
        <th>郵便番号</th><td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th><td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th><td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th><td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <% if @customer.is_deleted=="valid" %>
          <td class="text-success"><%= Customer.is_deleteds_i18n[:"#{@customer.is_deleted}"] %></td>
        <% else %>
          <td class="text-secondary"><%= Customer.is_deleteds_i18n[:"#{@customer.is_deleted}"] %></td>
        <% end %>
      </tr>
      <tr>
        <th></th>
        <td>
          <%= link_to "編集する",edit_admin_customer_path(@customer.id),class:"btn btn-success" %>
          <%= link_to "注文履歴一覧を見る",'/admin',class:"btn btn-primary ml-5" %>
        </td>
      </tr>

    </table>
  </div>

</div>