config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to:'homes#top'
    get 'about'=>'homes#about',as:'about'

    get 'customers/my_page'=>'customers#show'
    get 'customers/information/edit'=>'customers#edit'
    patch 'customers/information'=>'customers#update'
    get 'customers/confirm'=>'customers#confirm'
    patch '/customers/withdrawal'=>'customers#withdrawal'

    resources:items,only:[:index,:show]
    resources:cart_items,only:[:index,:create,:update,:destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources:orders,only:[:new,:create,:index,:show] do
      collection do
        post 'confirm'
        get  'done'
      end
    end
    resources:addresses,only:[:create,:index,:edit,:update,:destroy]
  end

  get 'admin'=>'admin/homes#top',as:'admin'

  namespace :admin do
    resources:items,only:[:new,:create,:index,:show,:edit,:update]
    resources:genres,only:[:create,:index,:edit,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:orders,only:[:show,:update] do
      resources:order_details,only:[:update]
    end
  end


  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many:order_details,dependent: :destroy
  belongs_to:customer

  validates :customer_id,presence:true
  validates :delivery_postal_code,presence:true
  validates :delivery_address,presence:true
  validates :delivery_name,presence:true
  validates :postage,presence:true
  validates :payment,presence:true
  validates :payment_method,inclusion: ["credit_card","transfer"]
  validates :order_status,inclusion: ["not_payment","payment_confirmation","production","preparing_to_ship","sent"]


  enum order_status:{not_payment:0,payment_confirmation:1,production:2,preparing_to_ship:3,sent:4}
  enum payment_method:{credit_card:0,transfer:1}

  def get_postage
    800
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action:authenticate_admin!
  def show
    @order=Order.find(params[:id])
    @order_details=@order.order_details
    @total=0


  end

  def update
    @order=Order.find(params[:id])
    @order_details=@order.order_details
    if @order.update(order_params)
      if @order.order_status=="payment_confirmation"
         @order_details.each do |order_detail|
           order_detail.update(production_status: "wait_production")
         end
      else
      end
       flash[:notice]="更新が成功しました"
       redirect_to admin_order_path(@order.id)
    else
       render:show
    end
  end

  private

  def order_params
    params.require(:order).permit(:customer_id,:delivery_postal_code,:delivery_address,:delivery_name,:postage,:payment,:payment_method,:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">

  <div class="m-3">
    <% if @order.errors.any? %>
      <h5><%=@order.errors.count %>件のエラーが発生しました。</h5>
      <% @order.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>
  </div>

  <h5 class="m-5"><span class="bg-light">　注文履歴詳細　</span></h5>

  <table class="table table-borderless text-nowrap">
    <tr>
      <th style="width: 20%">購入者</th><td style="width: 80%" ><%= link_to "#{@order.customer.last_name}#{@order.customer.first_name}",admin_customer_path(@order.id),class:"text-dark border-bottom border-dark" %></td>
    </tr>

    <tr>
      <th>注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>

    <tr>
      <th>配送先</th><td>〒<%= @order.delivery_postal_code %> <%= @order.delivery_address %><br>
                         <%= @order.delivery_name %></td>
    </tr>

    <tr>
      <th>支払方法</th><td><%= Order.payment_methods_i18n[:"#{@order.payment_method}"] %></td>
    </tr>

    <tr>
      <th>注文ステータス</th>
      <td><%= form_with model:@order,url:admin_order_path(@order.id),method: :patch do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]},{},{class:"text-center"} %>
            <%= f.submit"更新",class:"btn btn-success btn-sm ml-3" %>
          <% end %>
      </td>
    </tr>
  </table>

  <div class="row">
    <div class="col-lg-8">
      <table class="table table-borderless text-nowrap">
        <thead>
          <tr class="table-secondary">
            <th style="width: 30%">商品名</th>
            <th style="width: 20%">単価（税込）</th>
            <th style="width: 10%">数量</th>
            <th style="width: 10%">小計</th>
            <th style="width: 30%">制作ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @order_details.each do |order_detail| %>

          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td class="text-center"><%= order_detail.amount %></td>
            <td><%= (order_detail.price*order_detail.amount).to_s(:delimited) %></td>
                <% @total +=order_detail.price*order_detail.amount %>

            <td><%= form_with model:[@order,order_detail],url:admin_order_order_detail_path(@order.id,order_detail.id),method: :patch do |f| %>
                <%= f.select :production_status, OrderDetail.production_statuses.keys.map {|k| [I18n.t("enums.order_detail.production_status.#{k}"), k]},{},{class:"text-center"} %>
                <%= f.submit"更新",class:"btn btn-success btn-sm btn-sm ml-3" %>
                <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="offset-1 col-lg-3 align-self-end">
      <table>
        <tr>
          <th>商品合計</th><td class="text-right pl-3"><%= @total.to_s(:delimited) %>円</td>
        </tr>

        <tr>
          <th>送料</th><td class="text-right pl-3"><%=@order.postage.to_s(:delimited) %>円</td>
        </tr>

        <tr>
          <th>請求金額合計</th><td class="text-right pl-3"><%= @order.payment.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>

  </div>

</div>