config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to:'homes#top'
    get 'about'=>'homes#about',as:'about'

    get 'customers/my_page'=>'customers#show'
    get 'customers/information/edit'=>'customers#edit'
    patch 'customers/information'=>'customers#update'
    get 'customers/confirm'=>'customers#confirm'
    patch '/customers/withdrawal'=>'customers#withdrawal'

    resources:items,only:[:index,:show]
    resources:cart_items,only:[:index,:create,:update,:destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources:orders,only:[:new,:create,:index,:show] do
      collection do
        post 'confirm'
        get  'done'
      end
    end
    resources:addresses,only:[:create,:index,:edit,:update,:destroy]
  end

  get 'admin'=>'admin/homes#top',as:'admin'

  namespace :admin do
    resources:items,only:[:new,:create,:index,:show,:edit,:update]
    resources:genres,only:[:create,:index,:edit,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:orders,only:[:show,:update] do
      resources:order_details,only:[:update]
    end
  end


  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to:customer

  validates:customer_id,presence:true
  validates:name,presence:true
  validates:postal_code,presence:true
  validates:address,presence:true

  def address_display
    '〒'+postal_code+' '+address+' '+name
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to:customer
  belongs_to:item

  validates:item_id,presence:true
  validates:customer_id,presence:true
  validates:amount,presence:true
  
  def subtotal
    item.with_tax_price*amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:cart_items, dependent: :destroy
  has_many:orders,     dependent: :destroy
  has_many:addresses,  dependent: :destroy

  validates :last_name,presence:true
  validates :first_name,presence:true
  validates :last_name_kana,presence:true
  validates :first_name_kana,presence:true
  validates :postal_code,presence:true
  validates :address,presence:true
  validates :telephone_number,presence:true
  validates :is_deleted,inclusion: ["valid","withdrawal"]

  enum is_deleted: {valid: false,withdrawal: true},_suffix: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:items,dependent: :destroy
  validates :name,presence:true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached:image
  has_many:cart_items,    dependent: :destroy
  has_many:order_details, dependent: :destroy
  belongs_to:genre

  validates :name,         presence:true
  validates :introduction, length:{ minimum:1,maximum:255 }
  validates :genre_id,     presence:true
  validates :price,        presence:true
  validates :is_active,    inclusion: ["sale","suspended_sales"]


  enum is_active: {sale:true,suspended_sales:false}

  def with_tax_price
    (price*1.1).floor
  end

  def get_image(width,height)
    unless image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    image.variant(resize_to_limit:[width,height]).processed
  end


end

app/models/order.rb
class Order < ApplicationRecord
  has_many:order_details,dependent: :destroy
  belongs_to:customer

  validates :customer_id,presence:true
  validates :delivery_postal_code,presence:true
  validates :delivery_address,presence:true
  validates :delivery_name,presence:true
  validates :postage,presence:true
  validates :payment,presence:true
  validates :payment_method,inclusion: ["credit_card","transfer"]
  validates :order_status,inclusion: ["not_payment","payment_confirmation","production","preparing_to_ship","sent"]


  enum order_status:{not_payment:0,payment_confirmation:1,production:2,preparing_to_ship:3,sent:4}
  enum payment_method:{credit_card:0,transfer:1}

  def get_postage
    800
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to:order
  belongs_to:item

  enum production_status: {cannot_start:0,wait_production:1,making:2,produced:3}



  def with_tax_price
    (price*1.1).floor
  end

  def subtotal
    with_tax_price*amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action:authenticate_admin!

  def create
    @genre=Genre.new(genre_params)
    if @genre.save
      flash[:notice]="登録に成功しました。"
      redirect_to '/admin/genres'
    else
      @genres=Genre.all
      render:index
    end
  end

  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice]="変更しました。"
      redirect_to '/admin/genres'
    else
      render:edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action:authenticate_admin!
  
  def top
    @orders=Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action:authenticate_admin!
  
  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
       flash[:notice]="登録に成功しました。"
       redirect_to admin_item_path(@item.id)
    else
      render:new
    end
  end

  def index
    @items=Item.page(params[:page])
  end

  def show
    @item=Item.find(params[:id])
    
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice]="変更に成功しました。"
      redirect_to admin_item_path(@item.id)
    else
      render:edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #before_action:authenticate_admin!
    #before_action:authenticate_customer!,except:[:top,:about]





end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h2><a class=" text-dark p-3 mr-lg-5" href='/'><i class="fas fa-birthday-cake"></i>ながのCAKE</a></h2>
          <% if customer_signed_in? %>
            <div class="ml-lg-5">
            <%= 'ようこそ、'+current_customer.last_name+'さん！'%>
            </div>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧",'/admin/items',class:"btn btn-outline-secondary mr-3 navlink text-dark"%>
              </li>

              <li class="nav-item">
                <%= link_to "会員一覧",'/admin/customers',class:"btn btn-outline-secondary mr-3 navlink text-dark"%>
              </li>

              <li class="nav-item">
                <%= link_to "注文履歴一覧",'/admin',class:"btn btn-outline-secondary mr-3 navlink text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to "ジャンル一覧",'/admin/genres',class:"btn btn-outline-secondary mr-3 navlink text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to "ログアウト",destroy_admin_session_path,method: :delete,class:"btn btn-outline-secondary navlink text-dark" %>
              </li>

              <% elsif customer_signed_in? %>

              <li class="nav-item">
                <%= link_to "マイページ" ,'/customers/my_page',class:"btn btn-outline-secondary mr-3 navlink text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to "商品一覧",'/items',class:"btn btn-outline-secondary mr-3 navlink text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to "カート",'/cart_items',class:"btn btn-outline-secondary mr-3 navlink text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to "ログアウト",destroy_customer_session_path,method: :delete,class:"btn btn-outline-secondary navlink text-dark" %>
              </li>

            <% else %>
              <li class="nav-item">
                <%= link_to "About",about_path,class:"btn btn-outline-secondary mr-3 navlink text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to "商品一覧",'/items',class:"btn btn-outline-secondary mr-3 navlink text-dark" %>
               </li>

              <li class="nav-item">
                <%= link_to "新規登録",new_customer_registration_path,class:"btn btn-outline-secondary mr-3 navlink text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to "ログイン",new_customer_session_path,class:"btn btn-outline-secondary navlink text-dark" %>
              </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
    <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: message_type %>
    <% end %>

    <%= yield %>
    </main>

    <footer class="bg-secondary text-white mt-5 pt-5 pb-4">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-5 ml-md-5 mt-2">
            <p>長野県の洋菓子店</p>
            <h4><i class="fas fa-birthday-cake"></i>ながのCAKE</h4>
          </div>
          <div class="col-md-7 col-sm-6">
            <h6 class="mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>会社概要</li>
              <li>プライバシーポリシー</li>
            </ul>
          </div>
        </div>
      </div>

    </footer>

  </body>
</html>